[theme]
# Force the app to always use light mode
base="light"

# ASTRA design system colors
primaryColor="#D9D9D9"         # The green accent color you use
backgroundColor="#f9f9f9ff"      # Your exact Light Beige background
secondaryBackgroundColor="#F3F3F3" # White for sidebars/metrics
textColor="#222"            # Your exact Dark Gray text color
font="sans serif"
